// Code generated by "stringer -type=Status"; DO NOT EDIT.

package health

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Stopped-0]
	_ = x[Starting-1]
	_ = x[Healthy-2]
	_ = x[Unhealthy-3]
}

const _Status_name = "StoppedStartingHealthyUnhealthy"

var _Status_index = [...]uint8{0, 7, 15, 22, 31}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
