// Code generated by "gostringer -type=Status"; DO NOT EDIT.

package health

import "fmt"

const _Status_name_gostringer = "StoppedStartingHealthyUnhealthy"

var _Status_index_gostringer = [...]uint8{0, 7, 15, 22, 31}

func (i Status) GoString() string {
	if i < 0 || i >= Status(len(_Status_index_gostringer)-1) {
		return fmt.Sprintf("health.Status(%d)", i)
	}
	return "health." + _Status_name_gostringer[_Status_index_gostringer[i]:_Status_index_gostringer[i+1]]
}
